<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>1b40b0cb-3dbd-4b91-93e5-4f6258686090</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.9" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.14" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.14">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
        <PackageReference Include="SonarAnalyzer.CSharp" Version="10.27.0.140913">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.1" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Api\Middleware\" />
      <Folder Include="Api\Models\Tokens\" />
      <Folder Include="Infrastructure\Logging\" />
    </ItemGroup>

</Project>
